* Removed dvtm (finally learned to use tmux properly) * Added mplayer fix for stumpwm * Edited tmux keybindings * Edited zsh aliases * Edited zsh functions * Edited zsh profile * Synced backup script with the master copy on Eihort (epic network backup script) * *Big* tidy up of moviedb, removal of duplicated code across the scripts, more flexibility. * mplayer wrapper script to stop xscreensaver

diff --git a/bin/moviedb b/bin/moviedb
--- a/bin/moviedb
+++ b/bin/moviedb
@@ -1,6 +1,7 @@
 #!/bin/zsh
 
 export MOVIEPATH=`[ "$MOVIEPATH" = "" ] && echo "/home/barrucadu/video/movies" || echo $MOVIEPATH`
+export MOVIEPLAYER=`[ "$MOVIEPLAYER" = "" ] && echo "/home/barrucadu/bin/mplay" || echo $MOVIEPLAYER`
 
 function help ()
 {
@@ -19,12 +20,24 @@ function help ()
     echo "See the individual command help for more details."
     echo 
     echo "Return codes:"
-    echo "    1 = Unknown command."
+    echo "    7 = Unknown command."
+    echo "    8 = Missing movie player."
+    echo "    9 = Missing movie directories."
 
     echo "Maintainer: Michael Walker"
 }
 
 cmd=$1
+
+if [[ ! -e $MOVIEPLAYER ]] || [[ ! -x $MOVIEPLAYER ]]; then
+    echo "Missing movie player."
+    return 8
+fi
+
+if [[ ! -d $MOVIEPATH/ ]] || [[ ! -d $MOVIEPATH/by-director ]] || [[ ! -d $MOVIEPATH/by-genre ]] || [[ ! -d $MOVIEPATH/by-year ]]; then
+    echo "Missing movie directories."
+    return 9
+fi
 
 case $cmd in
     "add" | "lists" | "menu" | "play" | "query" | "fsck" | "misc")
@@ -33,5 +46,5 @@ case $cmd in
         help;;
     *)
         echo "Unknown command $cmd"
-        return 1;;
+        return 7;;
 esac
diff --git a/bin/moviedb-add b/bin/moviedb-add
--- a/bin/moviedb-add
+++ b/bin/moviedb-add
@@ -25,7 +25,6 @@ help()
     echo "Return codes:"
     echo "    1 = Movie file not found."
     echo "    2 = Error using director/genre directories."
-    echo "    3 = Missing movie folder(s)."
 }
 
 if [[ "$1" == "" ]] || [[ "$1" == "--help" ]]; then
@@ -37,36 +36,30 @@ movie="$1"    && shift
 director="$1" && shift
 year="$1"     && shift
 
-if [[ -d $MOVIEPATH/by-director ]] && [[ -d $MOVIEPATH/by-genre ]]; then
-    if [[ ! -e "$movie" ]]; then
-	echo "$movie not found."
-	return 1
-    fi
-
-    echo "Moving $movie to $MOVIEPATH/by-director/$director..."
-    chkdir "$MOVIEPATH/by-director/$director"
-    mv "$movie" "$MOVIEPATH/by-director/$director"
-
-    echo "Adding movie to year $year..."
-    chkdir "$MOVIEPATH/by-year/$year"
-    ln -s "../../by-director/$director/$movie" "$MOVIEPATH/by-genre/$year/$movie"
-
-    while [[ "$1" != "" ]]; do
-	echo "Adding movie to genre $1..."
-
-	chkdir "$MOVIEPATH/by-genre/$1"
-        out=$?
-        if [[ $out != 0 ]]; then
-            return $out
-        fi
-
-	ln -s "../../by-director/$director/$movie" "$MOVIEPATH/by-genre/$1/$movie"
-	shift
-    done
-
-    echo "Done."
-else
-    echo "\$MOVIEPATH = $MOVIEPATH"
-    echo "\$MOVIEPATH/by-director or \$MOVIEPATH/by-genre does not appear to exist."
-    return 3
+if [[ ! -e "$movie" ]]; then
+    echo "$movie not found."
+    return 1
 fi
+
+echo "Moving $movie to $MOVIEPATH/by-director/$director..."
+chkdir "$MOVIEPATH/by-director/$director"
+mv "$movie" "$MOVIEPATH/by-director/$director"
+
+echo "Adding movie to year $year..."
+chkdir "$MOVIEPATH/by-year/$year"
+ln -s "../../by-director/$director/$movie" "$MOVIEPATH/by-genre/$year/$movie"
+
+while [[ "$1" != "" ]]; do
+    echo "Adding movie to genre $1..."
+    
+    chkdir "$MOVIEPATH/by-genre/$1"
+    out=$?
+    if [[ $out != 0 ]]; then
+        return $out
+    fi
+    
+    ln -s "../../by-director/$director/$movie" "$MOVIEPATH/by-genre/$1/$movie"
+    shift
+done
+
+echo "Done."
