FIxed moviedb-add and moviedb-fsck, added many auto-fixing options to moviedb-fsck

diff --git a/bin/moviedb-fsck b/bin/moviedb-fsck
--- a/bin/moviedb-fsck
+++ b/bin/moviedb-fsck
@@ -2,22 +2,11 @@
 
 # A part of the moviedb set of scripts - for checking and repairing the database
 
-CHEDKDIRS=(by-director by-genre by-year)
+CHECKDIRS=(by-director by-genre by-year)
 CHECKLINKS=(by-genre by-year)
 
-help()
-{
-    echo "moviedb-fsck: A tool to check and repair the filesystem database."
-    echo
-    echo "Usage: moviedb-fsck"
-    echo
-    echo "Return codes:"
-    echo "    1 = All errors found were fixed."
-    echo "    2 = Errors found were not fixed."
-}
-
 # Strip the video extension from files
-stripext()
+function stripext()
 {
     fname=$1
     case $fname in
@@ -32,10 +21,28 @@ stripext()
     esac
 }
 
+# Attempt to fix a symlink
+function fixlink()
+{
+    link=$1
+    blink=`stripext $link`
+    file=`moviedb query file "$blink" | sed 's:.*/by-director:../../by-director:'`
+
+    if [[ -f $file ]]; then
+	rm $link
+	ln -s $file $link
+	return 0
+    else
+	return 1
+    fi
+}
+
 # Check for non-directories and empty directories, deleting or ignoring them.
-checkdirs()
+function checkdirs()
 {
     dir=$1
+    verbose=$2
+    deldirs=$3
     ret=0
 
     pushd $dir
@@ -47,33 +54,45 @@ checkdirs()
                 ret=1
             fi
 
-            while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
-                echo -n "$dir/$subdir is not a directory, delete or ignore? [di] "
-                read answer
-            done
-
-            case "$answer" in
-                "d")
-                    rm "$dir/$subdir";;
-                "i")
-                    ret=2;;
-            esac
+	    if $deldirs; then
+		echo "$dir/$subdir is not a directory, deleting."
+		rm "$dir/$subdir"
+	    else
+		while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
+                    echo -n "$dir/$subdir is not a directory, delete or ignore? [di] "
+                    read answer
+		done
+		
+		case "$answer" in
+                    "d")
+			rm "$dir/$subdir";;
+                    "i")
+			ret=2;;
+		esac
+	    fi
         elif [[ "`ls "$subdir" | wc -l`" == "0" ]]; then
             if [[ $ret == 0 ]]; then
                 ret=1
             fi
 
-            while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
-                echo -n "$dir/$subdir is empty, delete or ignore? [di] "
-                read answer
-            done
-
-            case "$answer" in
-                "d")
-                    rmdir "$dir/$subdir";;
-                "i")
-                    ret=2;;
-            esac
+	    if $deldirs; then
+		echo "$dir/$subdir is empty, deleting."
+		rm "$dir/$subdir"
+	    else
+		while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
+                    echo -n "$dir/$subdir is empty, delete or ignore? [di] "
+                    read answer
+		done
+		
+		case "$answer" in
+                    "d")
+			rmdir "$dir/$subdir";;
+                    "i")
+			ret=2;;
+		esac
+	    fi
+	elif $verbose; then
+	    echo "$dir/$subdir OK."
         fi
     done
     popd
@@ -82,9 +101,12 @@ checkdirs()
 }
 
 # Check for broken and non-relative symbolic links
-checklinks()
+function checklinks()
 {
     dir=$1
+    verbose=$2
+    fixlinks=$3
+    dellinks=$4
     ret=0
 
     pushd $dir
@@ -97,70 +119,97 @@ checklinks()
                 if [[ $ret == 0 ]]; then
                     ret=1
                 fi
-                
-                while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
-                    echo -n "$dir/$subdir/$link is not a symbolic link, delete or ignore? [di] "
-                    read answer
-                done
-                
-                case "$answer" in
-                    "d")
-                        rm "$dir/$subdir/$link";;
-                    "i")
-                        ret=2;;
-                esac
+               
+		if $dellinks; then
+		    echo "$dir/$subdir/$link is not a symbolic link, deleting."
+		    rm "$dir/$subdir/$link"
+		else
+                    while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]]; do
+			echo -n "$dir/$subdir/$link is not a symbolic link, delete or ignore? [di] "
+			read answer
+                    done
+                    
+                    case "$answer" in
+			"d")
+                            rm "$dir/$subdir/$link";;
+			"i")
+                            ret=2;;
+                    esac
+		fi
             elif file $link | grep -q "broken symbolic"; then
                 if [[ $ret == 0 ]]; then
                     ret=1
                 fi
                 
-                while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]] && [[ "$answer" != "f" ]]; do
-                    echo -n "$dir/$subdir/$link is a broken symbolic link, delete, fix or ignore? [dfi] "
-                    read answer
-                done
-                
-                case "$answer" in
-                    "d")
-                        rm "$dir/$subdir/$link";;
-                    "f")
-                        blink=`stripext $link`
-                        file=`moviedb query file "$blink" | sed 's:.*/by-director:../../by-director:'`
-                        if [[ -f $file ]]; then
-                            rm $link
-                            ln -s $file $link
-                        else
-                            echo "Could not repair automatically, fix manually."
-                            ret=2
-                        fi;;
-                    "i")
-                        ret=2;;
-                esac
+		if $fixlinks; then
+		    echo "$dir/$subdir/$link is a broken symbolic link, fixing."
+		    if ! fixlink $link; then
+			if $dellinks; then
+			    echo "Could not repair automatically, deleting."
+			    rm "$dir/$subdir/$link"
+			else
+			    echo "Could not repair automatically, fix manually."
+			fi
+                    fi
+		elif $dellinks; then
+		    echo "$dir/$subdir/$link is a broken symbolic link, deleting."
+		    rm "$dir/$subdir/$link"
+		else
+                    while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]] && [[ "$answer" != "f" ]]; do
+			echo -n "$dir/$subdir/$link is a broken symbolic link, delete, fix or ignore? [dfi] "
+			read answer
+                    done
+                    
+                    case "$answer" in
+			"d")
+                            rm "$dir/$subdir/$link";;
+			"f")
+			    if ! fixlink $link; then
+				echo "Could not repair automatically, fix manually."
+				ret=2
+                            fi;;
+			"i")
+                            ret=2;;
+                    esac
+		fi
             elif file $link | grep -q -v "../../by-director"; then
                 if [[ $ret == 0 ]]; then
                     ret=1
                 fi
                 
-                while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]] && [[ "$answer" != "f" ]]; do
-                    echo -n "$dir/$subdir/$link is a non-relative symbolic link, delete, fix or ignore? [dfi] "
-                    read answer
-                done
-                
-                case "$answer" in
-                    "d")
-                        rm "$dir/$subdir/$link";;
-                    "f")
-                        blink=`stripext $link`
-                        file=`moviedb query file "$blink" | sed 's:.*/by-director:../../by-director:'`
-                        if [[ -f $file ]]; then
-                            rm $link
-                            ln -s $file $link
-                        else
-                            echo "Could not repair automatically, fix manually."
-                            ret=2
-                        fi;;
-                    "i")
-                        ret=2;;
-                esac
+		if $fixlinks; then
+		    echo "$dir/$subdir/$link is a non-relative symbolic link, fixing."
+		    if ! fixlink $link; then
+			if $dellinks; then
+			    echo "Could not repair automatically, deleting."
+			    rm "$dir/$subdir/$link"
+			else
+			    echo "Could not repair automatically, fix manually."
+			fi
+                    fi
+		elif $dellinks; then
+		    echo "$dir/$subdir/$link is a non-relative symbolic link, deleting."
+		    rm "$dir/$subdir/$link"
+		else
+                    while [[ "$answer" != "d" ]] && [[ "$answer" != "i" ]] && [[ "$answer" != "f" ]]; do
+			echo -n "$dir/$subdir/$link is a non-relative symbolic link, delete, fix or ignore? [dfi] "
+			read answer
+                    done
+                    
+                    case "$answer" in
+			"d")
+                            rm "$dir/$subdir/$link";;
+			"f")
+			    if ! fixlink $link; then
+				echo "Could not repair automatically, fix manually."
+				ret=2
+                            fi;;
+			"i")
+                            ret=2;;
+                    esac
+		fi
+	    elif $verbose; then
+		echo "$dir/$subdir/$link OK."
             fi
         done
         popd
@@ -170,16 +219,59 @@ checklinks()
     return $ret
 }
 
-if [[ "$1" == "help" ]]; then
-    help
-    return 0
-fi
+function help()
+{
+    echo "moviedb-fsck: A tool to check and repair the filesystem database."
+    echo
+    echo "Usage: moviedb-fsck [-v] [-d] [-l] [-f] [-y]"
+    echo
+    echo "Arguments:"
+    echo "    -v = Be verbose."
+    echo "    -d = Delete problematic directories."
+    echo "    -l = Delete problematic links."
+    echo "    -f = Attempt to fix problematic links. If fixed and -l is given, do not delete."
+    echo "    -y = Auto-fix (implies -d -l -f)."
+    echo
+    echo "Return codes:"
+    echo "    1 = All errors found were fixed."
+    echo "    2 = Errors found were not fixed."
+    echo "    3 = Unknown argument."
+}
+
+verbose=false
+deldirs=false
+dellinks=false
+fixlinks=false
+
+while [[ "$1" != "" ]]; do
+    case $1 in
+	"help")
+	    help
+	    return 0;;
+	"-v")
+	    verbose=true;;
+	"-d")
+	    deldirs=true;;
+	"-l")
+	    dellinks=true;;
+	"-f")
+	    fixlinks=true;;
+	"-y")
+	    deldirs=true
+	    dellinks=true
+	    fixlinks=true;;
+	*)
+	    echo "Unknown argument '$1'."
+	    return 3;;
+    esac
+    shift
+done
 
 retcode=0
 
 # Check directories
 for dir in $CHECKDIRS; do
-    checkdirs $MOVIEPATH/$dir
+    checkdirs $MOVIEPATH/$dir $verbose $deldirs
 
     out=$?
     if [[ $out > $retcode ]]; then
@@ -188,8 +280,8 @@ for dir in $CHECKDIRS; do
 done
 
 # Check links
-for dir in $CHECKDIRS; do
-    checklinks $MOVIEPATH/$dir
+for dir in $CHECKLINKS; do
+    checklinks $MOVIEPATH/$dir $verbose $fixlinks $dellinks
 
     out=$?
     if [[ $out > $retcode ]]; then
