Suggest `brew` package in command_not_found_handler

diff --git a/zsh/.zsh/profile b/zsh/.zsh/profile
--- a/zsh/.zsh/profile
+++ b/zsh/.zsh/profile
@@ -116,13 +116,34 @@ export PS3="${fyellow}%Bselect%b:${default} "
 
 function command_not_found_handler() {
   if [[ -e $1 ]] && [[ -z $2 ]]; then
+    # Open it if it's a text file.
     if file $1 | grep ' text$' >/dev/null; then
       $EDITOR $1
     else
       file $1
     fi
+
   else
-    echo "Command not found: $*" >&2
+    # Attempt to suggest a command to install it otherwise.
+    local command=""
+    local found=false
+
+    if type brew &>/dev/null; then
+      pkg=`brew which-formula $1`
+      if [[ ! -z $pkg ]]; then
+        found=true
+        command="brew install $pkg"
+      fi
+    fi
+
+    # TODO: Add command-not-found (see nixos-channel-scripts issue #4)
+
+    if $found; then
+      echo "The program '$1' is not currently installed. You can install it by typing:" >&2
+      echo "  $command" >&2
+    else
+      echo "Command not found: '$1'" >&2
+    fi
   fi
 }
 
